### PR TITLE
Added gradle build.

### PR DESCRIPTION
**Pull request by psh**
Thought you might like a small addition to the project :)

### CODE REVIEW

**Comment by pforhan** [comment]
Looks like an accidental build file include: https://github.com/psh/wannabe/blob/gradle/swing/build/resources/main/example-heightmap.png

**Comment by pforhan** [comment]
I use GH rarely enough now that I can't remember how to comment directly on a binary file.  Can I? :cry:

**Comment by psh** [comment]
I moved the file to comply with the Maven (and by extension Gradle) standard convention for where resource files should live: https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

The build-tool takes care of copying the file into the runtime classpath.

If you prefer to have the file live in the src/main/java hierarchy I can whip up a quick copy task in the gradle build to copy the file into the classpath at runtime.

**Comment by pforhan** [comment]
src/main/resources is fine, but build/resources/main is not.  And there should only be one image file checked in.

**Comment by psh** [comment]
I missed that it was in the build directory - I'll fix that when I get home.  My bad!

**Comment by psh** [comment]
File removed.

**Comment by pforhan** [comment]
I should rip out the maven files now, I suppose.

**Comment by pforhan** [comment]
... and I really need to get an android lib and testbed going, there's lots of things I need to pull out of the swing impl and a second one would be the way to find them.

**Pull request merged**
